### ISSUE TITLE
Extending REST module

### ISSUE THREAD

**Issue by MrHash** [Codeception/module-rest#12]
When extending the `REST` module to make a custom `Helper` class my test is unable to see my custom functions e.g.

```php
final class Api extends Codeception\Module\REST
{
    public function seeSomething(): void
    {
        //my helper
    }
}
```
The error received is `[RuntimeException] Call to undefined method ApiTester::seeSomething` while other modules such as `Cli` are extendable as expected. Please advise.

**Comment by Naktibalda** [comment]
Please show configuration of the suite.

**Comment by MrHash** [comment]
Here is the suite configuration. As mentioned other helper extending `Cli` works fine.
```
suites:
  api:accounting:
    actor: ApiTester
    path: app/accounting/tests/e2e
    modules:
      enabled:
        - Asserts:
        - \Helper\App:
        - \Helper\Api:
            url: http://local.domain.name
            depends: PhpBrowser
            part: Json
```
