### ISSUE TITLE
Trying to get coverage report

### ISSUE THREAD

**Issue by pesseyjulien** [Codeception/module-rest#79]
Hi,

It seems that using the Rest module with Phpbrowser does not work for 'coverage'

Example running `bin/codecept run --coverage --coverage-xml --coverage-html` :
![Capture d’écran 2022-04-05 à 19 35 42](https://user-images.githubusercontent.com/10850944/161816574-69374ca0-4fc5-4174-9bea-8b8fb70dc389.jpg)

Here is the config of `api.suite.yml` :

```
class_name: ApiTester
coverage:
  enabled: true
  remote: true
  remote_context_options:
    http:
      timeout: 60
    ssl:
      verify_peer: false
modules:
    enabled:
        - Asserts
        - Symfony:
              kernel_class: App\Kernel
              app_path: 'src'
              environment: 'test'
        - REST:
              depends: PhpBrowser
        - Doctrine2:
              depends: Symfony
              cleanup: true
```

We are mainly using the `send()` method of the `ApiTesterActions`.

We followed the doc here : https://codeception.com/docs/11-Codecoverage

We also followed the instructions to installed the `c3.php` file (https://github.com/Codeception/c3)

What are we missing ?

Thanks in advance for your help,
Julien
